Added samples for Bedrock https call with Sigv4 in .NET
aws-samples/sigv4-signing-examples pull request #3
Opened 2024-10-18 13:25 UTC by sssumarss

*Issue #, if available:*

*Description of changes:*
- Added samples for Bedrock https call with Sigv4 in .NET
- Added support for http post request
- Refactored signing code into a separate class

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-18 14:18 UTC, jhart0 requested changes
Core changes look good - just a couple of minor comments

Can you also please update the readme so it's clear to viewers what each sample does / how to run each one.

2024-10-18 14:18 UTC, jhart0 commented on .DS_Store
Please remove these files. The .gitignore was mean to catch them.

2024-10-18 14:18 UTC, jhart0 commented on no-sdk/.DS_Store
Please remove these files. The .gitignore was mean to catch them.

2024-10-18 14:18 UTC, jhart0 commented on no-sdk/dotnet/.DS_Store
Please remove these files. The .gitignore was mean to catch them.

2024-10-18 14:18 UTC, jhart0 commented on no-sdk/dotnet/Program.cs
Can you add a conditional here so a user can choose which example they want to run i.e. likely one or the other

2024-10-18 16:47 UTC, sssumarss commented
Thanks for reviewing the code. Addressed all the review points above. Please have a look.

2024-10-23 13:26 UTC, jhart0 commented
LGTM!

2024-10-23 13:26 UTC, merged